# Generated by Django 4.2.5 on 2023-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tender",
            options={"ordering": ["-date_modified"]},
        ),
        migrations.RenameField(
            model_name="tender",
            old_name="dateModified",
            new_name="date_modified",
        ),
        migrations.RemoveField(
            model_name="tender",
            name="id",
        ),
        migrations.AlterField(
            model_name="tender",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="tender_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
